### ISSUE TITLE
About demo-data

### ISSUE THREAD

**Issue by hjames1** [YutingPKU/SingleCell-Multiomics#1]
Thanks for your tutorial! 
However, where can I download the demo-data, there are no 'cellranger-res/Pre-B/outs/filtered_feature_bc_matrix/'  and 'cellranger-count/' paths on your github.

**Comment by YutingPKU** [comment]
Hi！Due to the project is unpublished, so the raw count is not available at present.  However, I uploaded the processed data (most .rds object) to Baidu Netdisk. The download link is updated in the README.md. I'm not sure whether you can download the demo-data from Baidu Netdisk. If you meet any question, please let me know.

**Comment by hjames1** [comment]
Hi! Thank you for your sharing, now all the scripts can run smoothly. I'll close this issue.
